# Generated by Django 5.0.4 on 2024-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="All_users_model",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_Profile", models.FileField(upload_to="images/")),
                ("User_Email", models.EmailField(max_length=50)),
                ("User_Status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "all_users",
            },
        ),
        migrations.CreateModel(
            name="Comparison_graph",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("MobileNet", models.CharField(max_length=10, null=True)),
                ("DenseNet", models.CharField(max_length=10, null=True)),
                ("Vgg16", models.CharField(max_length=10, null=True)),
                ("Xception", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Comparisongraph",
            },
        ),
        migrations.CreateModel(
            name="Densenet_model",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Densenet",
            },
        ),
        migrations.CreateModel(
            name="Mobilenet_model",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Mobilenet",
            },
        ),
        migrations.CreateModel(
            name="Train_test_split_model",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("training_accuracy", models.CharField(max_length=10, null=True)),
                ("validation_accuracy", models.CharField(max_length=10, null=True)),
                ("testing_accuracy", models.CharField(max_length=10, null=True)),
                ("classes_accuracy", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Traintestsplit",
            },
        ),
        migrations.CreateModel(
            name="Vgg16_model",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Vgg16",
            },
        ),
        migrations.CreateModel(
            name="Xception_model",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Xception",
            },
        ),
    ]
