# Generated by Django 5.0.4 on 2024-04-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="All_model",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_Name", models.CharField(max_length=10, null=True)),
                ("model_accuracy", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "Allmodel",
            },
        ),
        migrations.CreateModel(
            name="wildfire_Dataset",
            fields=[
                ("Data_id", models.AutoField(primary_key=True, serialize=False)),
                ("Image", models.ImageField(upload_to="media/")),
            ],
            options={
                "db_table": "wildfireDataset",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("Feed_id", models.AutoField(primary_key=True, serialize=False)),
                ("Rating", models.CharField(max_length=100, null=True)),
                ("Review", models.CharField(max_length=225, null=True)),
                ("Sentiment", models.CharField(max_length=100, null=True)),
                ("datetime", models.DateTimeField(auto_now=True)),
                (
                    "Reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_details",
            },
        ),
    ]
